<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 8</title>
</head>
<body>
	<h1>Заняття 8</h1><br>
	<h3>Завдання 9</h3><br>
	"Написать функцию, которая переворачивает строку. Было \"abcde\", должна выдать \"edcba\".
	Ввод текста реализовать с помощью формы.<br><hr>
	<b><?=$message?></b>
	<form method = "post">
		<textarea name = "text" cols = "25" maxlength = '255' rows = '3'></textarea>
		<input type="submit" name="submit" value = "Надіслати"/>
	</form><br>
	<?php echo requestGet('ba');?>
</body>
</html>