<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 8</title>
</head>
<body>
	<h1>Заняття 8</h1><br>
	<h3>Завдання 3</h3><br>
	Есть текстовый файл. Необходимо удалить из него все слова, длина которых превыщает N символов.
	Значение N задавать через форму. Проверить работу на кириллических строках - найти ошибку, найти решение..<br><hr>
	<b><?=$message?></b>
	<form method="post">
		<form method = "post">
	<input type="number" name="length" placeholder = "Довжина строки" min = "1" max = "20"/>
	<input type="submit" name="submit"/ value="Надіслати">
	</form><br>
</body>
</html>