<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 8</title>
</head>
<body>
	<h1>Заняття 8</h1><br>
	<h3>Завдання 1</h3><br>
	Создать форму с двумя элементами textarea. При отправке формы скрипт должен выдавать только те слова, которые есть и в первом и во втором поле ввода. Реализацию этой логики необходимо поместить в функцию getCommonWords($a, $b), которая будет возвращать массив с общими словами.<br><hr>
	<b><?=$message?></b>
	<form method="post">
		<textarea name="t1" placeholder="Поле вводу 1" rows="4" cols="33"></textarea><br>
		<textarea name="t2" placeholder="Поле вводу 2" rows="4" cols="33"></textarea><br>
		<input type="submit" name="submit" value="Надіслати">
	</form>
	<?php print_r($comwords)?>
</body>
</html>