<!DOCTYPE html>
<html>
<meta charset="utf-8">
<head>
	<title>Hometask 8</title>
</head>
<body>
	<h1>Заняття 8</h1><br>
	<h3>Завдання 2</h3><br>
	Создать форму с элементом textarea. При отправке формы скрипт должен выдавать ТОП3 длинных слов в тексте. Реализовать с помощью функции.<br><hr>
	<b><?=$message?></b>
	<form method="post">
		<textarea name="t1" placeholder="Поле вводу 1" rows="4" cols="33"></textarea><br>
		<input type="submit" name="submit" value="Надіслати">
	</form><br>
	<?php print_r($b); ?>
</body>
</html>